version: 1
services:
  docker_jekins:
    user:root
    restart: always
    image: jekinsci/blueocean
    container_name: jekins
    ports: 
      - 8080:8080
      - 50000:50000
      volumes: 
        - /home/jekins/jekins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  docker_nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes: 
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/webserver/static/dist:/usr/share/nginx/html
      